### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by fangyyyyy** [HKUDS/LLMRec#10]
There're two errors when running the file gpy_user_profiling.py:
1. urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x145b449d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

2. urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='llms-se.baidu-int.com', port=8200): Max retries exceeded with url: /chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x145b449d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Do you know to solve the problems?🙏🙏 Thank you!

**Comment by weiwei1206** [comment]
We sincerely appreciate your unwavering interest in our work🌺🌺. When employing LLM, we utilize the API offered by Baidu and rely on the token provided internally by Baidu. To utilize ChatGPT, it is necessary to register an OpenAI account with a legitimate credit card and phone number from an eligible region, subsequently utilizing the token provided exclusively by OpenAI.

PS: If obtaining a legitimate phone number from an eligible region poses any inconvenience, you may explore the option of acquiring a virtual online number from this website: https://sms-activate.org/en/info/ChatGPT. We sincerely hope that this information proves helpful to you🙏🏻🙏🏻. Once again, we extend our heartfelt gratitude for your interest in our work❤️❤️.

**Comment by fangyyyyy** [comment]
您好！我是张方圆，您的来信我已收到，会尽快查看回复！祝您身体健康，工作顺利，学习愉快！

**Comment by SitaramSpanda** [comment]
How about URL : http://llms-se.baidu-int.com:8200/chat/completions

**Comment by fangyyyyy** [comment]
您好！我是张方圆，您的来信我已收到，会尽快查看回复！祝您身体健康，工作顺利，学习愉快！
