### ISSUE TITLE
Error: the first step by run:"python3 gpt_ui_aug.py"

### ISSUE THREAD

**Issue by qdbje** [HKUDS/LLMRec#11]
Step1：
run 
python3 gpt_ui_aug.py

error message:

Traceback (most recent call last):
  File "/Users/~/Documents/dev/ai/LLMRec-main/LLM_augmentation_construct_prompt/gpt_ui_aug.py", line 85, in <module>
    candidate_indices = pickle.load(open(file_path + 'candidate_indices','rb'))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'candidate_indices'

**Comment by weiwei1206** [comment]
Thank you sincerely for showing interest in our work, and we genuinely appreciate your question🙏🏻. We have made available all the data files required to run LLMRec at the provided link(https://drive.google.com/drive/folders/1BGKm3nO4xzhyi_mpKJWcfxgi3sQ2j_Ec). We would like to kindly request you to please verify if you have successfully downloaded all the files, including the "candidate indices" file. Your thorough attention to this matter would be greatly appreciated🤝🤝.
