### ISSUE TITLE
Which python version

### ISSUE THREAD

**Issue by patelrajnath** [HKUDS/LLMRec#13]
Hi, thanks for this great work. 

I was trying setup the virtual env, and when I run "pip install -r requirements.txt", I get errors related to version. 
For example - 
_ERROR: Could not find a version that satisfies the requirement anaconda-client==1.11.0 (from versions: 1.1.1, 1.2.2)
ERROR: No matching distribution found for anaconda-client==1.11.0_

**I'm using Python 3.10.13 with Ubuntu 22.04.3 LTS.**

I was wondering if there is any specific requirement of Python version. I anyone can suggest how to resolve these. 

Best Regards
Raj

**Comment by weiwei1206** [comment]
Dear Raj,
My Python version is "Python 3.9.13 (main, Aug 25 2022, 23:26:10)".  
The file "requirements.txt" is generated directly from my environment and serves as a helpful reference.

We sincerely appreciate your attention to our work🤝🤝.

Best,
WEI
