### ISSUE TITLE
Could not install packages

### ISSUE THREAD

**Issue by chengl-amd** [HKUDS/LLMRec#6]
Hi, when I perform: 

pip install -r requirements.txt

Error comes out as:
Processing /home/ktietz/src/ci/alabaster_1611921544520/work (from -r requirements.txt (line 6))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/ktietz/src/ci/alabaster_1611921544520/work'

requirements.txt refers some package paths that don't exist in my local PC.

**Comment by weiwei1206** [comment]
I wanted to inform you that I've already addressed this matter. You might find it helpful to consider installing the required packages mentioned in the .py file's header.

Your understanding and cooperation are greatly appreciated.

Warm regards,
WEI
