### ISSUE TITLE
No such file or directory: 'candidate_indices'

### ISSUE THREAD

**Issue by chengl-amd** [HKUDS/LLMRec#7]
Hi there，

when I run python gpt_ui_aug.py, the error is:

Traceback (most recent call last):
  File "/cling/xcosdaem495/LLMRec/LLM_augmentation_construct_prompt/gpt_ui_aug.py", line 86, in <module>
    candidate_indices = pickle.load(open(file_path + 'candidate_indices','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'candidate_indices'

Can you please help?

**Comment by weiwei1206** [comment]
I am confident that the "Netflix" dataset already includes the file you mentioned. However, I kindly suggest double-checking for any minor errors on your end :)    ^_^
