### ISSUE TITLE
寻找URL

### ISSUE THREAD

**Issue by xxxxxxing** [HKUDS/LLMRec#9]
运行gpt_user_profiling文件时，open ai.api_base = "http://llms-se.baidu-int.com:8200"这行代码报错，这个URL我应该去哪里找。谢谢你的回答。

**Comment by weiwei1206** [comment]
We deeply appreciate your unwavering interest in our work~🌹🌹. When utilizing LLM, we rely on the API provided by Baidu and their internal key. To utilize ChatGPT, please follow these two steps:
i) Comment out the line of code openai.api_base = "http://llms-se.baidu-int.com:8200" and replace it with the following line: openai.api_key = "your key".
ii) Utilize the key exclusively provided by OpenAI in this code: "Authorization": "Bearer your key", replacing "your key" with your actual key.

If acquiring a valid phone number from an eligible region proves to be inconvenient, you may consider exploring the alternative of obtaining a virtual online number from the following website: https://sms-activate.org/en/info/ChatGPT. We genuinely hope that this information proves to be of assistance to you🙏🏻🙏🏻🙏🏻. Once again, we extend our heartfelt gratitude for your unwavering interest in our work. 🙏🏻❤️
